DELETE FROM public.news
WHERE version = '2.0.4';

INSERT INTO public.news (version, title, title_en, body, body_en, tag, tag_en, published_at)
VALUES (
  '2.0.4',
  'Habi 2.0.4: Đồng bộ an tâm, tiến bộ rõ ràng hơn ✨',
  'Habi 2.0.4: Safer sync, clearer progress ✨',
  E'Đồng bộ & đăng nhập an tâm hơn:\n\n• Khi mất mạng, hoạt động vẫn được lưu trên thiết bị. Khi có mạng trở lại, Habi sẽ báo trạng thái và cho phép đồng bộ lại.\n• Đăng nhập Google và khôi phục dữ liệu sau khi cài lại app hoặc kết nối lại ổn định hơn.\n\nSao & Rank rõ ràng hơn:\n\n• Home, Analytics, Rank và Friends giờ hiển thị cùng một tổng số sao nhiệm vụ kiếm được trong năm nay.\n• Bỏ check, xóa hoặc lưu trữ hoạt động sẽ trừ đúng số sao đã nhận. Rank đã đạt vẫn được giữ nguyên.\n\nChallenge đáng tin cậy hơn:\n\n• “Hôm nay” luôn theo đúng ngày trên thiết bị của bạn.\n• Challenge liên kết, việc bổ sung ngày còn thiếu và nhắc nhở hoạt động ổn định hơn sau khi mất mạng hoặc đóng app.\n\nMượt mà & dễ dùng hơn:\n\n• Chạm vào từng ngày trên heatmap để xem chi tiết.\n• Analytics Month giờ hiển thị đúng tháng thực tế.\n• Calendar, onboarding và giao diện Android thích ứng tốt hơn với nhiều kích thước màn hình.\n\nGóp ý thuận tiện hơn:\n\n• Báo lỗi từ Profile hoặc ngay trên màn hình News khi bản tin không tải được.\n• Đã bỏ mục phản hồi trùng trong Settings và tính năng chọn ảnh mới cho Challenge.\n\nNếu bạn quay lại app sau ít nhất 24 giờ kể từ hoạt động đầu tiên đủ điều kiện, Habi có thể mời bạn đánh giá ứng dụng một lần.\n\nCập nhật lên Habi 2.0.4 và tiếp tục tiến bộ, từng ngôi sao một 💚',
  E'More reliable sync and sign-in:\n\n• Your activities are saved on your device when you are offline. Once you are back online, Habi shows the sync status and lets you try again.\n• Google Sign-In and data recovery after reinstalling or reconnecting are now more reliable.\n\nClearer stars and Rank:\n\n• Home, Analytics, Rank, and Friends now show the same total of task stars earned this year.\n• Unchecking, deleting, or archiving an activity removes the correct number of stars. Your achieved Rank stays intact.\n\nMore reliable Challenges:\n\n• “Today” now follows your device’s local date.\n• Linked Challenges, filling in missed days, and reminders work more reliably after going offline or closing the app.\n\nSmoother and easier to use:\n\n• Tap any heatmap day to see its details.\n• Analytics Month now shows the actual calendar month.\n• Calendar, onboarding, and Android layouts adapt better to different screen sizes.\n\nEasier feedback:\n\n• Report an issue from Profile or directly from the News screen when updates fail to load.\n• Removed the duplicate feedback entry in Settings and photo selection for new Challenge content.\n\nHabi may show a one-time review prompt when you return at least 24 hours after your first eligible activity.\n\nUpdate to Habi 2.0.4 and keep moving forward, one star at a time 💚',
  'Có gì mới',
  'What''s new',
  '2026-09-16T00:00:00+07:00'
);
